# Generated by Django 3.2.9 on 2021-11-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='has_permission_to',
            field=models.IntegerField(null=True),
        ),
    ]
